### PR TITLE
Validate instance type before CloudFormation

### LINKED ISSUE #1006: Supported instance type being rejected in region eu-north-1
A user reached out with the following issue using `ecs-cli version 1.18.1 (7e9df84)`:

`$ ecs-cli up  --capability-iam --size 4 --instance-type c4.large --launch-type EC2`

```
WARN[0000] You will not be able to SSH into your EC2 instances without a key pair. 
INFO[0001] Using recommended Amazon Linux 2 AMI with ECS Agent 1.39.0 and Docker version 18.09.9-ce 
INFO[0002] Created cluster                               cluster=test region=eu-north-1
FATA[0003] Error executing 'up': ValidationError: Parameter EcsInstanceType failed to satisfy constraint: must be a valid EC2 instance type.
	status code: 400, request id: <redacted>
```

`$ ecs-cli up  --capability-iam --size 4 --instance-type t3.medium --launch-type EC2`

```
WARN[0000] You will not be able to SSH into your EC2 instances without a key pair. 
INFO[0001] Using recommended Amazon Linux 2 AMI with ECS Agent 1.39.0 and Docker version 18.09.9-ce 
INFO[0002] Created cluster                               cluster=test region=eu-north-1
FATA[0003] Error executing 'up': ValidationError: Parameter EcsInstanceType failed to satisfy constraint: must be a valid EC2 instance type.
	status code: 400, request id: <redacted>
```

I validated that `t3.medium` and `c4.large` are indeed available in `eu-north-1`:
`AWS_REGION=eu-north-1 aws ec2 describe-instance-types --query InstanceTypes[].InstanceType`

I asked them to try cli version 1.18.0 due to the changes introduce in 1.18.1 that affected how we validate instance types: https://github.com/aws/amazon-ecs-cli/pull/958

It works in version 1.18.0:
`$ ecs-cli up  --capability-iam --size 4 --instance-type t3.medium --launch-type EC2`
```
WARN[0000] You will not be able to SSH into your EC2 instances without a key pair. 
INFO[0001] Using recommended Amazon Linux 2 AMI with ECS Agent 1.39.0 and Docker version 18.09.9-ce 
INFO[0001] Created cluster                               cluster=test region=eu-north-1
INFO[0002] Waiting for your cluster resources to be created... 
INFO[0002] Cloudformation stack status                   stackStatus=CREATE_IN_PROGRESS
INFO[0064] Cloudformation stack status                   stackStatus=CREATE_IN_PROGRESS
```

This seems to be a potential regression from version 1.18.0 -> 1.18.1 with how we're validating input instance types.

**NOTE:** The scope of affected regions and instance types is currently unknown.

### PR DESCRIPTION
**Pull request by sonofachamp**
CloudFormation will try to validate the Default ECSInstanceType parameter
based on the AllowedValues field which is problematic in regions that do
not support our default t2.micro instance type such as eu-north-1.

Resolves #1006

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
- [X] Unit tests passed
- [x] Integration tests passed
- [X] Unit tests added for new functionality
- [X] Listed manual checks and their outputs in the comments ([example](https://github.com/aws/amazon-ecs-cli/pull/750#issuecomment-472623042))
- [ ] Link to issue or PR for the integration tests:

**Documentation**
- [ ] Contacted our doc writer
- [ ] Updated our README
----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: ecs-cli/modules/cli/cluster/cluster_app.go [hunk 1]
```diff
@@ -400,6 +418,36 @@ func retrieveInstanceType(cfnParams *cloudformation.CfnStackParams) (string, err
...
+func validateInstanceType(instanceType string, supportedInstanceTypes []string) error {
+	found := false
+	for _, it := range supportedInstanceTypes {
+		if it == instanceType {
+			found = true
+			break
+		}
+	}
+	if !found {
+		return fmt.Errorf(invalidInstanceTypeFmt, instanceType, supportedInstanceTypes)
```
Comment (iamhopaul123) [inline ecs-cli/modules/cli/cluster/cluster_app.go:445]: I wonder if we need to output the whole supported instanceType because that will be huge. I would make this func return boolean and handle the "not found" error out of the function.

File: ecs-cli/modules/cli/cluster/cluster_app.go [hunk 2]
```diff
@@ -314,6 +319,24 @@ func createCluster(context *cli.Context, awsClients *AWSClients, commandConfig *
 	}
 
 	if launchType == config.LaunchTypeEC2 {
+		instanceType, err := populateInstanceTypeParameter(cfnParams)
+		if err != nil {
+			return err
+		}
+		supportedInstanceTypes, err := awsClients.EC2Client.DescribeInstanceTypeOfferings(commandConfig.Region())
+		if err != nil {
+			return errors.Wrapf(err, "No instance type found in region %s", commandConfig.Region())
```
Comment (iamhopaul123) [inline ecs-cli/modules/cli/cluster/cluster_app.go:328]: The error returns by `DescribeInstanceTypeOfferings` might not only because "no instance type found"? It could be other reason. And also I guess "No instance type found in region %s" is already wrapped up in `DescribeInstanceTypeOfferings`?

File: ecs-cli/modules/cli/cluster/cluster_app.go [hunk 3]
```diff
@@ -400,6 +418,36 @@ func retrieveInstanceType(cfnParams *cloudformation.CfnStackParams) (string, err
...
+		logrus.Infof("Defaulting instance type to %s", cloudformation.DefaultECSInstanceType)
+
+		cfnParams.Add(ParameterKeyInstanceType, cloudformation.DefaultECSInstanceType)
+
+		return cloudformation.DefaultECSInstanceType, nil
+	} else if err != nil {
+		return "", err
+	}
+
+	return aws.StringValue(param.ParameterValue), err
```
Comment (iamhopaul123) [inline ecs-cli/modules/cli/cluster/cluster_app.go:433]:
```suggestion
	param, err := cfnParams.GetParameter(ParameterKeyInstanceType)
	if err == nil {
	        return aws.StringValue(param.ParameterValue), err
	}
	if err == cloudformation.ParameterNotFoundError {
		logrus.Infof("Defaulting instance type to %s", cloudformation.DefaultECSInstanceType)

		cfnParams.Add(ParameterKeyInstanceType, cloudformation.DefaultECSInstanceType)

		return cloudformation.DefaultECSInstanceType, nil
	}
	return "", err
```
Maybe like this?

File: ecs-cli/modules/cli/cluster/cluster_app.go [hunk 4]
```diff
@@ -314,6 +319,24 @@ func createCluster(context *cli.Context, awsClients *AWSClients, commandConfig *
...
+		if err != nil {
+			return err
+		}
+		supportedInstanceTypes, err := awsClients.EC2Client.DescribeInstanceTypeOfferings(commandConfig.Region())
+		if err != nil {
+			return errors.Wrapf(err, "No instance type found in region %s", commandConfig.Region())
+		}
+
+		if err = validateInstanceType(instanceType, supportedInstanceTypes); err != nil {
+			// if we detect the default value is unsupported then we'll suggest to the user overriding the value with the appropriate flag
```
[the remark this answers is not in the document]
Comment (sonofachamp) [reply ecs-cli/modules/cli/cluster/cluster_app.go:332]: The wrapped error includes the list of supported values in the output.

File: ecs-cli/modules/cli/cluster/cluster_app.go (hunk 1 above)
Comment (sonofachamp) [reply ecs-cli/modules/cli/cluster/cluster_app.go:445]: It's unwieldy I agree, but it's helpful to the user, otherwise they'll just be asking themselves "well what are the supported instance types". I think it should stay.

Comment (iamhopaul123) [reply ecs-cli/modules/cli/cluster/cluster_app.go:445]: :+1:

File: ecs-cli/modules/cli/cluster/cluster_app.go (hunk 2 above)
Comment (sonofachamp) [reply ecs-cli/modules/cli/cluster/cluster_app.go:328]: I copied this exactly as it was previously, but I'll update it to wrap with "failed to describe instance type offerings: %w". I think this is what you're suggesting?

Comment (iamhopaul123) [reply ecs-cli/modules/cli/cluster/cluster_app.go:328]: yes that's my bad. thanks for fixing that!

Comment (iamhopaul123) [reply ecs-cli/modules/cli/cluster/cluster_app.go:328]: maybe just "describe instance type offerings: %w" would be enough.

File: ecs-cli/modules/cli/cluster/cluster_app.go (hunk 3 above)
Comment (sonofachamp) [reply ecs-cli/modules/cli/cluster/cluster_app.go:433]: It's more standard to left-align the happy path. We should check for non-nil errors first and handle those.

**Comment by sonofachamp** [comment]
## Sample output runs

### Unsupported instance type flag
`./bin/local/ecs-cli up --region eu-north-1 --capability-iam --launch-type EC2 --instance-type t2.micro`

```
WARN[0000] You will not be able to SSH into your EC2 instances without a key pair. 
WARN[0001] Default instance type t2.micro not supported in region eu-north-1. Override the default instance type with the --instance-type flag and provide a supported value. 
FATA[0001] Error executing 'up': instance type t2.micro not supported in region eu-north-1: instance type t2.micro not found in list of supported instance types [r5d.16xlarge t3.micro i3.4xlarge c5d.18xlarge i3.xlarge m5d.24xlarge g4dn.8xlarge r5.xlarge r5.16xlarge c5.4xlarge c5d.4xlarge g4dn.4xlarge m5.2xlarge m5.metal r5d.2xlarge g4dn.16xlarge c5d.metal m5d.8xlarge m5d.metal m5d.12xlarge i3.large t3.2xlarge d2.2xlarge c5.12xlarge c5d.12xlarge r5.8xlarge t3.nano r5d.xlarge r5d.metal m5d.xlarge c5d.xlarge m5d.2xlarge m5.16xlarge r5d.24xlarge c5.large t3.medium r5.2xlarge c5d.large i3.2xlarge g4dn.2xlarge r5.metal r5d.12xlarge c5d.24xlarge c5.9xlarge g4dn.xlarge m5d.16xlarge r5d.8xlarge r5d.4xlarge r5.large m5.xlarge d2.8xlarge d2.xlarge m5.4xlarge m5.large m5.24xlarge r5d.large r5.4xlarge c5d.2xlarge m5d.large r5.24xlarge t3.small c5.2xlarge i3.16xlarge r5.12xlarge c5.metal i3.8xlarge c5.xlarge m5.12xlarge c5.18xlarge c5d.9xlarge m5.8xlarge t3.xlarge c5.24xlarge t3.large m5d.4xlarge g4dn.12xlarge d2.4xlarge]
```

### Default instance type is unsupported in specified region

`./bin/local/ecs-cli up --region eu-north-1 --capability-iam --launch-type EC2`

```
WARN[0000] You will not be able to SSH into your EC2 instances without a key pair. 
INFO[0000] Defaulting instance type to t2.micro         
WARN[0001] Default instance type t2.micro not supported in region eu-north-1. Override the default instance type with the --instance-type flag and provide a supported value. 
FATA[0001] Error executing 'up': instance type t2.micro not supported in region eu-north-1: instance type t2.micro not found in list of supported instance types [r5d.12xlarge d2.xlarge r5d.24xlarge c5.xlarge t3.2xlarge m5.large i3.large g4dn.4xlarge c5d.metal m5d.large m5.24xlarge m5.metal r5.16xlarge t3.large g4dn.2xlarge t3.xlarge i3.4xlarge c5.large m5d.8xlarge r5d.4xlarge c5d.4xlarge m5d.16xlarge t3.nano g4dn.16xlarge r5d.large r5.12xlarge c5.12xlarge r5.metal c5.metal c5.18xlarge i3.xlarge c5d.large c5.2xlarge r5.xlarge g4dn.xlarge m5d.4xlarge m5d.2xlarge t3.medium m5d.metal m5d.12xlarge c5d.2xlarge m5.4xlarge m5.8xlarge m5.12xlarge c5.4xlarge r5.large m5.2xlarge m5d.xlarge i3.16xlarge c5d.9xlarge t3.small r5.8xlarge i3.2xlarge r5d.xlarge r5d.metal m5.xlarge r5d.8xlarge c5d.18xlarge t3.micro c5d.xlarge d2.4xlarge d2.2xlarge g4dn.8xlarge c5d.24xlarge g4dn.12xlarge m5.16xlarge c5.9xlarge r5.24xlarge r5.2xlarge c5.24xlarge m5d.24xlarge r5d.2xlarge r5d.16xlarge c5d.12xlarge r5.4xlarge d2.8xlarge i3.8xlarge]
```

### Instance type flag is supported in specified region

`./bin/local/ecs-cli up --region eu-north-1 --capability-iam --launch-type EC2 --instance-type t3.small`

```
WARN[0000] You will not be able to SSH into your EC2 instances without a key pair. 
INFO[0002] Using recommended Amazon Linux 2 AMI with ECS Agent 1.39.0 and Docker version 18.09.9-ce 
INFO[0003] Created cluster                               cluster=pnt-raw region=eu-north-1
INFO[0005] Waiting for your cluster resources to be created... 
INFO[0005] Cloudformation stack status                   stackStatus=CREATE_IN_PROGRESS
INFO[0067] Cloudformation stack status                   stackStatus=CREATE_IN_PROGRESS
INFO[0130] Cloudformation stack status                   stackStatus=CREATE_IN_PROGRESS
VPC created: <redacted>
Security Group created: <redacted>
Subnet created: <redacted>
Subnet created: <redacted>
Cluster creation succeeded.
```

**Comment by sonofachamp** [comment]
I still need to run the integration tests against these proposed changes.

**Comment by sonofachamp** [comment]
Integ tests are passing now. I had to add `Default: ""` for the `EcsInstanceType` parameter for the `TestCreateClusterWithFargateService` to pass even though this parameter has no significance in the context of Fargate. Ideally this would be an "optional parameter" so CloudFormation doesn't kick it out if we don't provide a value, or we would not provide this parameter in the template for Fargate.

**Comment by elbow** [comment]
Would be keen to get this merged.
Currently you can't use ecs-cli up in af-south-1 since this new region doesn't have t2.micro.
