### PR TITLE
Cluster and Region flags allowed both before and after the subcommand for compose commands. 

### LINKED ISSUE #270: ecs-cli compose service create --cluster option ignored?
Hello,

It seems to me that --cluster option is ignored when using "ecs-cli compose service" command, respecting only the ecs.cluster value configured in the ~/.ecs/config file.

When used without previous ecs-cli configure command (i.e. the cluster value in config is empty) the command fails with "cluster not found" message. If some cluster is defined in the ~/.ecs/config file and the --configure option value differs the command works with the cluster name specified in the config file.

```
ecs-cli --version
ecs-cli version 0.6.0 (1053c82)
```

Possible bug?
Pavel

### PR DESCRIPTION
**Pull request by PettitWesley**
closes #270

Examples:
```sh
$ ecs-cli compose --cluster other --region us-east-2 up
$ ecs-cli compose up --cluster other --region us-east-2
```
Both will produce the desired behavior (cluster and region in the config is overridden) and both produce the same behavior.

#### Unit tests:
```sh
$ make test
```

##### After subcommand:
```sh
$ ecs-cli compose create --cluster other --region us-east-2
$ ecs-cli compose start --cluster other --region us-east-2
$ ecs-cli compose up --cluster other --region us-east-2
$ ecs-cli compose ps --cluster other --region us-east-2
$ ecs-cli compose scale 2 --cluster other --region us-east-2
$ ecs-cli compose run --cluster other --region us-east-2
$ ecs-cli compose stop --cluster other --region us-east-2
$ ecs-cli compose down --cluster other --region us-east-2
```

##### Before subcommand:
```sh
$ ecs-cli compose --cluster other --region us-east-1 create
$ ecs-cli compose --cluster other --region us-east-1 start
$ ecs-cli compose --cluster other --region us-east-1 scale 2
$ ecs-cli compose --cluster other --region us-east-1 stop
$ ecs-cli compose --cluster other --region us-east-1 up
$ ecs-cli compose --cluster other --region us-east-1 down
```

##### After subcommand:
```sh
ecs-cli compose service create --cluster other --region us-east-1
ecs-cli compose service start --cluster other --region us-east-1
ecs-cli compose service up --cluster other --region us-east-1
ecs-cli compose service ps --cluster other --region us-east-1
ecs-cli compose service scale 2 --cluster other --region us-east-1
ecs-cli compose service stop --cluster other --region us-east-1
ecs-cli compose service down --cluster other --region us-east-1
```

##### Before subcommand:
```sh
ecs-cli compose service --cluster other --region us-east-1 start
ecs-cli compose service --cluster other --region us-east-1 scale 2
ecs-cli compose service --cluster other --region us-east-1 stop
ecs-cli compose service --cluster other --region us-east-1 ps
ecs-cli compose service --cluster other --region us-east-1 up
ecs-cli compose service --cluster other --region us-east-1 down
```

##### Before Before Subcommand:
```sh
ecs-cli compose --cluster other --region us-east-1 service start
ecs-cli compose --cluster other --region us-east-1 service scale 2
ecs-cli compose --cluster other --region us-east-1 service stop
ecs-cli compose --cluster other --region us-east-1 service ps
ecs-cli compose --cluster other --region us-east-1 service up
ecs-cli compose --cluster other --region us-east-1 service down
```
(presumably no one will ever use the command this way, but just in case they do- it works!)

### CODE REVIEW

File: ecs-cli/modules/commands/compose/compose_command.go [hunk 1]
```diff
@@ -103,6 +103,10 @@ func createCommand(factory composeFactory.ProjectFactory) cli.Command {
 		Name:   "create",
 		Usage:  "Creates an ECS task definition from your compose file. Note that we do not recommend using plain text environment variables for sensitive information, such as credential data.",
 		Action: compose.WithProject(factory, compose.ProjectCreate, false),
+		Flags: []cli.Flag{
```
Comment (yinshiua) [inline ecs-cli/modules/commands/compose/compose_command.go]: You will also do the same with `compose service` subcommands.

Comment (PettitWesley) [inline ecs-cli/modules/commands/compose/compose_command.go]: Done! I had to rewrite some of the code tho to make it search recursively up the context, but now it works, and will continue to work in the future no matter how nested the subcommands are. These flags can be placed anywhere in the command.

File: ecs-cli/modules/config/params.go [hunk 2]
```diff
@@ -37,6 +37,19 @@ func (p *CliParams) GetCfnStackName() string {
 	return fmt.Sprintf("%s%s", p.CFNStackNamePrefix, p.Cluster)
 }
 
+// Searches as far up the context as necesarry. This function works no matter
+// how many layers of nested subcommands there are. It is more powerful
+// than merely calling context.String and context.GlobalString
+func recursiveFlagSearch(context *cli.Context, flag string) string {
```
Comment (yinshiua) [inline ecs-cli/modules/config/params.go]: Nice. We can also use this on `--project-name` flag and other compose flags.
