### PR TITLE
Add waiter for service creation - Fix for issue 79

### LINKED ISSUE #79: 'compose service up' does not ensure service is created before trying to start it
I just ran 'compose service up' which failed with the error

"Please use 'create' command to create the service 'my-service-name' first"

Usually it works, but it appears that it is possible under some circumstances for 'up' to  try to 'start' when 'create' has failed (or at least before it is complete)

### PR DESCRIPTION
**Pull request by dickmao**
*Issue #, if available:* #79 

*Description of changes:* Insert a `waitForServiceDescribable()` in `Up()`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by allisaurus** [comment]
Hi @dickmao - before we can work with this PR, could you please add the [license language from our PR template](https://github.com/aws/amazon-ecs-cli/blob/master/.github/PULL_REQUEST_TEMPLATE.md) to the description and rebase off of the latest changes in the `dev` branch? 

Thank you for taking the time to submit this!

File: ecs-cli/modules/cli/compose/entity/service/service_test.go [hunk 1]
```diff
@@ -767,6 +779,60 @@ func getUpdateServiceMockClient(t *testing.T,
...
+			gomock.Any(), // networkConfig
+			gomock.Any(), // launchType
+			gomock.Any(), // healthCheckGracePeriod
+		).Do(func(a, b, c, d, e, f, g, h interface{}) {
+			observedTaskDefID := b.(string)
+			assert.Equal(t, taskDefID, observedTaskDefID, "Task Definition name should match")
+		}).Return(nil),
+
+		mockEcs.EXPECT().DescribeService(gomock.Any()).Return(getDescribeServiceTestResponse(nil), nil),
+		mockEcs.EXPECT().DescribeService(gomock.Any()).Return(getDescribeServiceTestResponse(createdService), nil).MaxTimes(2),
```
Comment (allisaurus) [inline ecs-cli/modules/cli/compose/entity/service/service_test.go]: these 2 lines (the two DescribeService calls - one returning nil, the 2nd service details) seem specific to testing the case where the service is not immediately describable. Can we make that apparent by renaming this func `getCreateServiceWithDelayMockClient` ?

File: ecs-cli/modules/cli/compose/entity/service/service_test.go [hunk 2]
```diff
@@ -767,6 +779,60 @@ func getUpdateServiceMockClient(t *testing.T,
...
+	ctrl *gomock.Controller,
+	taskDefinition ecs.TaskDefinition,
+	taskDefID string,
+	registerTaskDefResponse ecs.TaskDefinition,
+) *mock_ecs.MockECSClient {
+
+	mockEcs := mock_ecs.NewMockECSClient(ctrl)
+
+	createdService := &ecs.Service{
+		TaskDefinition: aws.String("arn/test-task-def"),
```
Comment (allisaurus) [inline ecs-cli/modules/cli/compose/entity/service/service_test.go]: * Since we're passing in `taskDefID`, can we set the service TaskDefinition to reflect that? ("arn/" + taskDefID)
* Then we can also assert it's the same task def passed into UpdateService() on line 822 (similar to how we're verifying CreateService() in put on lines 815-817)

**Comment by dickmao** [comment]
Made the requested changes.  Thanks.

File: ecs-cli/modules/cli/compose/entity/service/service_test.go (hunk 2 above)
Comment (allisaurus) [reply ecs-cli/modules/cli/compose/entity/service/service_test.go]: Ah, you're right - we don't pass in the task definition if it's the same as what's present in the existing service. Thanks for clarifying!

**Comment by SoManyHs** [comment]
@dickmao  Thanks for this sumbission. LGTM -- could you squash your commits and provide a descriptive commit message that summarizes the fix? Something like:
```
Wait for service to be created on before starting it

Previously, `compose service up` would fail sporadically due to a race condition where the call to start the service would be made before the the CreateService call to ECS had completed. This change adds a waiter to ensure that the service has been created before being launched.

Fixes #79
```

Thanks so much!

**Comment by dickmao** [comment]
Squashed.  Thanks.
