### PR TITLE
Set up automatic pull for EC2 instance types

### LINKED ISSUE #954: c5d.24xlarge is not supported
#### Summary

I tried to call **ecs-cli up** with instance type c5d.24xlarge, however, it gives me the error
```
Error executing 'up': ValidationError: Parameter EcsInstanceType failed to satisfy constraint: must be a valid EC2 instance type.\n\tstatus code: 400, request id: ea84537f-2e77-4467-9a4d-6c634490dc03
```
However, when I try to launch container instance from console, this type is supported. 

Seems it is due to in the cloud formation template, this type is not added to your hardcoded [allowed value list](https://github.com/aws/amazon-ecs-cli/blob/3970a6c1f38bc750ff9c068f53220aa177c7df54/ecs-cli/modules/clients/aws/cloudformation/cluster_template.go#L114).

Can you update the list to include the newest EC2 instance types?

#### Description

* Which specific command was run? 
```
ecs-cli up --instance-type c5d.24xlarge --region eu-west-1 --image-id ami-0f1670c2113013c34 ...
```
* Which version of the CLI you are using? (Run: `ecs-cli --version`)
* Which version of Go are you using? (Run: `go version`)
* What platform are you using to run ECS CLI commands? (E.g. Linux, macOS, Windows)

#### Config files

* docker-compose.yml

* ecs-params.yml

* ~/.ecs/config

#### Expected Behavior
The cluster can be successfully created.
#### Observed Behavior
```
Error executing 'up': ValidationError: Parameter EcsInstanceType failed to satisfy constraint: must be a valid EC2 instance type.\n\tstatus code: 400, request id: ea84537f-2e77-4467-9a4d-6c634490dc03
```

### PR DESCRIPTION
**Pull request by iamhopaul123**
Fixes #954.

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
- [x] Unit tests passed
- [ ] Integration tests passed
- [x] Unit tests added for new functionality
- [x] Listed manual checks and their outputs in the comments ([example](https://github.com/aws/amazon-ecs-cli/pull/750#issuecomment-472623042))
- [ ] Link to issue or PR for the integration tests:

**Documentation**
- [ ] Contacted our doc writer
- [ ] Updated our README
----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: ecs-cli/modules/clients/aws/ec2/client.go [hunk 1]
```diff
@@ -85,3 +87,29 @@ func (c *ec2Client) DescribeNetworkInterfaces(networkInterfaceIDs []*string) ([]
 	}
 	return response.NetworkInterfaces, nil
 }
+
+func (c *ec2Client) DescribeInstanceTypeOfferings(location string) ([]string, error) {
```
Comment (SoManyHs) [inline ecs-cli/modules/clients/aws/ec2/client.go]: Nit: I see in that location can be region or AZ. Since we only use region as specified in the input struct, would it help to name this as "region" instead of "location"?

Comment (iamhopaul123) [reply ecs-cli/modules/clients/aws/ec2/client.go]: Sure! Addressed.

**Comment by iamhopaul123** [comment]
## Manual test

`$ecs-cli up --instance-type c5d.24xlarge`

```
INFO[0000] Created cluster                               cluster=tutorial region=us-west-2
INFO[0001] Waiting for your cluster resources to be created... 
INFO[0001] Cloudformation stack status                   stackStatus=CREATE_IN_PROGRESS
INFO[0061] Cloudformation stack status                   stackStatus=CREATE_IN_PROGRESS
VPC created: vpc-0cd2ae4e0d0bb2fca
Subnet created: subnet-0387ca39986084594
Subnet created: subnet-074b81d5331f8be70
Cluster creation succeeded.
```
