### PR TITLE
Bug fix: log client creation doesn't change region in session

### LINKED ISSUE #644: --create-log-groups breaks --enable-service-discovery when logs are in a different region
There's a bug in the CLI when using Service Discovery and the `--create-log-groups` flag to create a log group in a different region than your ECS Service is in.

### Summary
Due to some [bad code using pointers](https://github.com/aws/amazon-ecs-cli/blob/master/ecs-cli/modules/clients/aws/cloudwatchlogs/client.go#L37) which I wrote a year ago, using `--create-log-groups` with a cross-region log configuration breaks the new Service Discovery feature. This is because `--create-log-groups` option changes the region that the CLI is using to whichever region the log group is located in. If the log group is located in a different region than the one you are launching your ECS Service into, this causes the problem to surface. Note that this only applies to Service Discovery. This is because AWS Clients are created in this order in the compose commands:

1. ECS Client
2. CloudWatch Logs Client
3. CloudFormation Client, Route53 Client, Service Discovery Client (used to enable Service Discovery)

When the buggy code that creates the CloudWatch Logs Client runs, it changes the region, which affects Service Discovery. However, the ECS Client is not affected, which is why this bug did not surface till now.

### Description
* Which version of the CLI you are using? 
1.9.0
* What platform are you using to run ECS CLI commands? (E.g. Linux, MacOSX, Windows)
Mac OS X

### Observed Behavior
```
$ ecs-cli compose service up --enable-service-discovery --cluster-config ireland --create-log-groups
INFO[0001] Using ECS task definition                     TaskDefinition="tmp:1"
WARN[0001] Failed to create log group example in us-east-2: The specified log group already exists 
INFO[0002] Waiting for the private DNS namespace to be created... 
INFO[0003] Cloudformation stack status                   stackStatus=CREATE_IN_PROGRESS
ERRO[0033] Failure event                                 reason="The VPC: vpc-0e1c2832ec0ab213b you provided is not authorized to make the association. (Service: AmazonRoute53; Status Code: 400; Error Code: InvalidVPCId; Request ID: 9ba36eed-d5bb-11e8-9341-5baec21c8a79)" resourceType="AWS::ServiceDiscovery::PrivateDnsNamespace"
FATA[0033] Failed to find output PrivateDNSNamespaceID in stack amazon-ecs-cli-setup-private-dns-namespace-compose3ec2-tmp 
```

The error is "The VPC you provided is not authorized to make the association" because the VPC is not in the same region as the CFN template.

### PR DESCRIPTION
**Pull request by PettitWesley**
Fixes #644, see issue for description of the issue.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: ecs-cli/modules/clients/aws/cloudwatchlogs/client_test.go [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+		Region: aws.String("eu-west-1"),
+	})
+	assert.NoError(t, err)
+	params := &config.CommandConfig{
+		Session: sess,
+	}
+
+	NewCloudWatchLogsClient(params, "us-east-2")
+
+	assert.Equal(t, "eu-west-1", aws.StringValue(params.Session.Config.Region), "Expected region to remain unchanged after call to NewCloudWatchLogsClient()")
```
Comment (SoManyHs) [inline ecs-cli/modules/clients/aws/cloudwatchlogs/client_test.go]: Looks good -- nittiest of nits, I'd maybe assign "eu-west-1" to a more descriptive variable, and modify the error message to maybe say something like "Expected configured region to remain unchanged..."

**Comment by PettitWesley** [comment]
@SoManyHs 

```
$ ecs-cli compose --ecs-params ecs-params-portlandia.yml service up --create-log-groups --enable-service-discovery --launch-type FARGATE --cluster sd-fluentd --region us-west-2
INFO[0000] Using ECS task definition                     TaskDefinition="fluent-collector:1"
INFO[0000] Created Log Group fluentd-sd2 in us-west-2   
INFO[0000] Waiting for the private DNS namespace to be created... 
INFO[0001] Cloudformation stack status                   stackStatus=CREATE_IN_PROGRESS
WARN[0031] Defaulting DNS Type to A because network mode was awsvpc 
INFO[0031] Waiting for the Service Discovery Service to be created... 
INFO[0031] Cloudformation stack status                   stackStatus=CREATE_IN_PROGRESS
INFO[0062] Created an ECS service                        service=fluent-collector taskDefinition="fluent-collector:1"
INFO[0062] Updated ECS service successfully              desiredCount=1 serviceName=fluent-collector
INFO[0077] (service fluent-collector) has started 1 tasks: (task 73576390-c5cd-4021-b2bc-241012579290).  timestamp="2018-10-24 18:53:37 +0000 UTC"
INFO[0138] Service status                                desiredCount=1 runningCount=1 serviceName=fluent-collector
INFO[0138] ECS Service has reached a stable state        desiredCount=1 runningCount=1 serviceName=fluent-collector
```
