### PR TITLE
Detect Graviton 2 instance as arm64 Fix #1113

### LINKED ISSUE #1113: Graviton2 instance type are detected as x86 instead of arm64
#### Summary

When creating cluster using ecs-cli, it gets AMI based on instance type. However the logic only supports a1 instances, but not [graviton2 instances](https://aws.amazon.com/ec2/instance-types/). I think the original code is from #695 (and hi @PettitWesley)

https://github.com/aws/amazon-ecs-cli/blob/mainline/ecs-cli/modules/clients/aws/amimetadata/client.go#L107

```go
func isARM64Instance(instanceType string) bool {
	r := regexp.MustCompile("a1\\.(medium|\\d*x?large)")
	if r.MatchString(instanceType) {
		return true
	}
	return false
}
```

#### Description

Command I run

```bash
ecs-cli up --capability-iam --size 2 --instance-type m6g.medium --cluster ecs-graviton2--region us-west-2
```

Version is 

```text
ecs-cli version 1.20.0 (7547c45)
```

#### Config files

N/A

#### Expected Behavior

The auto scale group contains 2 m6g.medium instances

#### Observed Behavior

Failed to launch EC2 instance because x86 AMI is used for arm64 instance

I can make a PR to fix that regex, but are there are any plan to publish [new releases](https://github.com/aws/amazon-ecs-cli/releases)?

### PR DESCRIPTION
**Pull request by pingleig**
Detect Graviton 2 arm instances as arm64 when choosing AMI.

Fix #1113 

----
Enter `[N/A]` in the box, if an item is not applicable to your change.

**Testing**
- [x] Unit tests passed
- [ ] Integration tests passed
- [x] Unit tests added for new functionality
- [x] Listed manual checks and their outputs in the comments ([example](https://github.com/aws/amazon-ecs-cli/pull/750#issuecomment-472623042))
- [ ] Link to issue or PR for the integration tests:

**Documentation**
- [N/A] Contacted our doc writer
- [N/A] Updated our README
----

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by pingleig** [comment]
Only did manual test, but I can run integration test if it is required cc @allisaurus 

```text
make bin/darwin-amd64/ecs-cli

./bin/darwin-amd64/ecs-cli up --capability-iam --size 2 --instance-type m6g.medium --cluster ecs-graviton2 --region us-west-2
WARN[0000] You will not be able to SSH into your EC2 instances without a key pair.
INFO[0007] Using Arm ecs-optimized AMI because instance type was m6g.medium
INFO[0008] Using recommended Amazon Linux 2 AMI with ECS Agent 1.48.1 and Docker version 19.03.13-ce
INFO[0008] Created cluster                               cluster=ecs-graviton2 region=us-west-2
INFO[0009] Waiting for your cluster resources to be created...
INFO[0009] Cloudformation stack status                   stackStatus=CREATE_IN_PROGRESS
INFO[0069] Cloudformation stack status                   stackStatus=CREATE_IN_PROGRESS
INFO[0130] Cloudformation stack status                   stackStatus=CREATE_IN_PROGRESS
VPC created: vpc-123
Security Group created: sg-123
Subnet created: subnet-123
Subnet created: subnet-123
Cluster creation succeeded.
```

And all the arm instances I found from public doc 

General Purpose

- t4g
- m6g
- m6gd
- a1

Compute Optimized

- c6g
- c6gd

Memory Optimized

- r6g
- r6gd

Accelerated Computing

- N/A

Storage Optimized

- N/A

btw: I am not sure if `.metal` instances are supported by ECS, I can change the regexp so `m6g.metal` etc.  use arm AMI as well.

**Comment by pingleig** [comment]
Checked `a1.metal` and it works, `mg6.metal` asks for 64 VPUs and is beyond my current quota (which is right at 64 .. hmm). Did a force push on my fork.


```text
ecs-cli up --capability-iam --size 1 --instance-type a1.metal --cluster ecs-graviton2-metal --region us-west-2
WARN[0000] You will not be able to SSH into your EC2 instances without a key pair.
INFO[0000] Using Arm ecs-optimized AMI because instance type was a1.metal
INFO[0000] Using recommended Amazon Linux 2 AMI with ECS Agent 1.48.1 and Docker version 19.03.13-ce
INFO[0000] Created cluster                               cluster=ecs-graviton2-metal region=us-west-2
INFO[0001] Waiting for your cluster resources to be created...
INFO[0001] Cloudformation stack status                   stackStatus=CREATE_IN_PROGRESS
INFO[0062] Cloudformation stack status                   stackStatus=CREATE_IN_PROGRESS
INFO[0123] Cloudformation stack status                   stackStatus=CREATE_IN_PROGRESS
VPC created: vpc-0a38aae81317f590d
Security Group created: sg-123
Subnet created: subnet-123
Subnet created: subnet-123
Cluster creation succeeded.
```

File: ecs-cli/modules/clients/aws/amimetadata/client_test.go [hunk 1]
```diff
@@ -54,7 +43,7 @@ func TestMetadataClient_GetRecommendedECSLinuxAMI(t *testing.T) {
 		},
 		{
 			// validate that we use the generic AMI for other instances
-			"t2.micro",
+			[]string{"t2.micro"},
```
Comment (allisaurus) [inline ecs-cli/modules/clients/aws/amimetadata/client_test.go]: since we're accounting for multiple instance types in the other AMI selection tests, can we add a few more "generic" types here? T3, M5a, C4, etc. (doesn't have to be exhaustive, but at least several popular ones that adhere to diff patterns)

**Review by allisaurus — COMMENTED** [review]
this is awesome @pingleig ! I have one minor comment re: expanding a test case but otherwise LGTM

File: ecs-cli/modules/clients/aws/amimetadata/client_test.go (hunk 1 above)
Comment (pingleig) [reply ecs-cli/modules/clients/aws/amimetadata/client_test.go]: Added in https://github.com/aws/amazon-ecs-cli/pull/1116/commits/2d6be87aae37b20fd540b9def04ee31ce516ccc9

**Review by allisaurus — APPROVED** [review]

**Comment by SoManyHs** [comment]
@mergifyio update
